select * from customer LIMIT 20
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as Total_Revenue
FROM customer
GROUP BY gender

--Q2. Which customers used a discount but 
--still spent more than the average purchase amount?
select customer_id, purchase_amount from
customer 
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)
from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating::numeric),2) as Average_Review_Rating
from customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC LIMIT 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(AVG(purchase_amount),2) as Average_Purchase_Amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, COUNT(customer_id) as total_customers, round(AVG(purchase_amount),2) as avg_spend, SUM(purchase_amount) as total_rev
FROM customer
GROUP BY subscription_status
ORDER BY total_rev DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, (100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)) as discount_rate
from customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT CASE WHEN previous_purchases = 1 THEN 'New' WHEN previous_purchases<20 THEN 'Returning' ELSE 'Loyal' END AS Segment, COUNT(*)
FROM customer
GROUP BY Segment

--Q8. What are the top 3 most purchased products within each category? 
WITH CTE as(select category,item_purchased,COUNT(customer_id)as total_orders, Row_Number()OVER(PARTITION BY category ORDER BY COUNT(item_purchased)DESC) as Rank
FROM customer
GROUP BY category, item_purchased)
select category,item_purchased,total_orders from CTE
where Rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, COUNT(customer_id) as repeat_buyers
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group, SUM(purchase_amount) as total_contribution
from customer
GROUP BY age_group
ORDER BY total_contribution DESC